stages:
  data_ingestion:
    cmd: python src\cnnClassifier\pipeline\stage_01_data_ingestion.py
    deps:
      - src\cnnClassifier\pipeline\stage_01_data_ingestion.py
      - config\config.yaml
    outs:
      - artifacts\data_ingestion\kidney-ct-scan-image
  prepare_base_model:
    cmd: python src\cnnClassifier\pipeline\stage_02_prepare_base_model.py
    deps:
      - src\cnnClassifier\pipeline\stage_02_prepare_base_model.py
      - config\config.yaml
    params:
      - IMAGE_SIZE
      - LEARNING_RATE
      - INCLUDE_TOP
      - WEIGHTS
      - CLASSES
    outs:
      - artifacts/prepare_base_model
    
  model_training:
    cmd: python src\cnnClassifier\pipeline\stage_03_model_training.py
    deps:
      - src\cnnClassifier\pipeline\stage_03_model_training.py
      - config\config.yaml
      - artifacts\data_ingestion\kidney-ct-scan-image
      - artifacts\prepare_base_model
    params:
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
      - IMAGE_SIZE
    outs:
      - artifacts/training/model.h5
  evaluation:
    cmd: python src\cnnClassifier\pipeline\stage_04_model_evaluation_with_mlflow.py
    deps:
      - src\cnnClassifier\pipeline\stage_04_model_evaluation_with_mlflow.py
      - artifacts/training/model.h5
      - config\config.yaml
      - artifacts\data_ingestion\kidney-ct-scan-image
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics: 
      - scores.json:
          cache: false
